export const GET_CLUBS_SUCCESS = 'GET_CLUBS_SUCCESS';
export const GET_CLUBS_LOADING = 'GET_CLUBS_LOADING';

// Auth
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// Errors
export const GET_ERRORS = 'GET_ERRORS'